#!/usr/bin/env bash

main() {

  spago build
  
    parcel ./index.html &
    inotifywait  -m ./src -e modify -e delete -e move | while read path action file; do
      echo "pureHMR- updating $action"
      spago build
    done
}

main
